"""Generate a compact structural map of production Python modules."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "CODEBASE_MAP.md"
EXCLUDED_DIRS = {
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "tests",
    "__pycache__",
    "venv",
}
EXCLUDED_FILES = {Path(__file__).name}


def source_files() -> list[Path]:
    """Return production Python files that should appear in the map."""
    files: list[Path] = []
    for path in ROOT.rglob("*.py"):
        relative = path.relative_to(ROOT)
        if any(part in EXCLUDED_DIRS for part in relative.parts):
            continue
        if path.name.startswith("test_") or path.name in EXCLUDED_FILES:
            continue
        files.append(path)
    return sorted(files, key=lambda path: path.relative_to(ROOT).as_posix())


def public_symbols(path: Path) -> list[tuple[str, str, int]]:
    """Return public top-level classes and functions from a Python file."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    symbols: list[tuple[str, str, int]] = []
    for node in tree.body:
        if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_"):
            continue
        kind = "class" if isinstance(node, ast.ClassDef) else "function"
        symbols.append((kind, node.name, node.lineno))
    return symbols


def render_map() -> str:
    """Render the repository's production Python structure as Markdown."""
    lines = [
        "# Codebase Map",
        "",
        "> Generated by `python scripts/generate_codebase_map.py`. Do not edit by hand.",
        "> Tests are intentionally omitted; use the `tests/` tree for behavior.",
        "",
    ]
    for path in source_files():
        relative = path.relative_to(ROOT).as_posix()
        lines.extend((f"## `{relative}`", ""))
        symbols = public_symbols(path)
        if not symbols:
            lines.append("- No public top-level classes or functions.")
        else:
            for kind, name, line in symbols:
                suffix = "" if kind == "class" else "()"
                lines.append(f"- **{kind}** `{name}{suffix}` — line {line}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Generate the map, or fail when the committed map is stale."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if CODEBASE_MAP.md does not match the current source tree",
    )
    args = parser.parse_args()
    rendered = render_map()

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print("CODEBASE_MAP.md is stale; run: python scripts/generate_codebase_map.py")
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print("Generated CODEBASE_MAP.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
